# This is a Jupyter notebook explaining the use of the Numpy.Random package as part of the Practical Assigment for the module Programming for Data Analysis 2018

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png">

## Problem statement:

1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

## Overall purpose of the package:

The numpy.random package is used to generate random numbers, it is a sub package of the Numpy package in Python. Numpy is an important package in Python as a lot of other packages depend on it but interacting with the package directly is nat actually that common, typically users would interact with it through the use of other packages such as Pandas or SciPy.

NumPy is a specialist package dealing with multi dimensional arrays or lists within lists, it is a very efficient method to perform operations on these arrays or matrices using algorithims that have been developed during research on numerical objects over the last half century.

See Quick start Tutorial https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html?highlight=quickstart; create two dimensional arrays. It is common to start with a csv imported in to Numpy, or in to Pandas which then uses NumPy in the background. If no csv file then you could use the Numpy.Random package to generate simulated data or arrays of numbers which follow a certian pattern.

Almost any interesting computing task e.g. image compression involves matrix operations at its most basic level and therefor NumPy is essential as the most efficient method of handling these operations.




## Rather than giving a summary of each individual function I would give a general explanation of what the library does and reference the various functions in that explanation.

Note that the numpy documentation already lists each function, what it does and what inputs and outputs it has. There's no point in just re-writing the documentation in your notebook. It would be better to write an illuminating notebook about what the library does overall.

Even though there are a lot of functions in the package, they all are actually variations on the basic notion of drawing values from probability distributions. For instance, the functions in "Simple random data" are just convenience functions for using the "Distributions" functions. There's not a lot to them and they're all quite similar.

Think of your notebook as giving the flavour of what the package is about, using plots, words, and code snippets. There's no point in re-writing the numpy documentation out.

Bell shaped curve

## Simple Random Data Section:

## 1. numpy.random.rand
Generates random numbers on the fly, depending on what paramaetrs are entered for the amount of rows and columns.
[0, 1) generates numbers between 0 and 1 but less than 1. The parameters should be positive integers. 


In [1]:
# import numpy package in order to use numpy
import numpy as np

In [2]:
x = np.random.rand(8)
x
# returns an array with 8 elements, what is in the brackets determines the shape of the array

array([0.45589039, 0.33120748, 0.41442395, 0.06114159, 0.96637819,
       0.34403348, 0.96114132, 0.38305831])

In [3]:
np.random.rand(3,2)
# returns an array with 3 rows and 2 columns, or 3 arrays within an array each with two elements

array([[0.4902017 , 0.0517357 ],
       [0.89580426, 0.35771414],
       [0.48521934, 0.55197466]])

In [4]:
np.random.rand(4,2)
# rerun the function, returns another array of same type but now with 4 rows and the numbers are different AND random

array([[0.79563074, 0.49381471],
       [0.40142239, 0.35872325],
       [0.96757874, 0.94179719],
       [0.26778343, 0.41981139]])

Generate a plot using matpoltlib indicating how rand function generates the random numbers

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x)
plt.show()

## Permutations Section:

## Distributions Section:

## 1. A 'Uniform Distribution', sometimes also known as a rectangular distribution, is a distribution that has constant probability.

Uniform function with first number being the lower boundary, second number being upper boundary and third being the size. Very similar to rand ( only between 0 and 1), uniform gives random numbers in any interval

In [ ]:
x = np.random.uniform(0, 1000, 10000)
x

In [ ]:
plt.hist(x)

The Hist function has chopped this into 10 "what is the correct term?"


## 2. A normal distribution
The probability density function of the normal distribution, first derived by De Moivre and 200 years later by both Gauss and Laplace independently [2], is often called the bell curve because of its characteristic shape (see the example below).

The normal distributions occurs often in nature. For example, it describes the commonly occurring distribution of samples influenced by a large number of tiny, random disturbances, each with its own unique distribution [2].

In [ ]:
x = np.random.normal(0, 0.1, 10000)
x

In [ ]:
plt.hist(x)

a way of generating numbers randomly, with values centered around 0 (here), huge proportion of values centered aroudn a single value

## Random Generator Section:
## The use of seeds in generating pseudorandom numbers.

Pseudorandom number generators are computer software packages that create numbers which appear to be random but in reality are predictable when the algorithm used to create these values is known. Computers are deterministic machines which means that their functions can be predictable and repeatable. This can be troublesome in the persuit of generating truely random numbers. 

Truely random number sequences can be generated by means of measuring the background radiation as it occurs in nature or other such processes. To avail of this truely random number generation, computer manufacturers would have to incorporate extra hardware and software into the design and assembly of their products, in order to measure this background radiation. This is not practical for a number of reasons, finacial reasons, efficiency, product size constraints etc. 

To combat this issue these generators make use of mathematical operations, series and special operators called "seeds". A seed is the key component in the generation of random numbers (a lot of computers use the state of the computer system as the seed, such as the time on the computer that the generator was run). Depending on what type of pseudorandom number generator being used, the seed feeds into a specified mathematical operation, such as the middle squares method or an operation that includes the apparent infinite series of decimals in the number "pi".

The result is a pseudorandom number or pseudorandom sequence of numbers depending on the mathematical operation. The seed is the crutial aspect in the generation of pseudorandom numbers. If the seed and the mathematical operation is known the pseudorandom numbers generated can be replicated, by anyone. Pseudorandom number generators are often used in cryptography, to encrypt messages and keep important data secure when being transmitted via the internet. To do this seeds have become extremely long and complicated so that it is next to impossible to crack the encryption, in any reasonable length of time. An interesting and informative youtube video from the Khan Academy, explaining the theory behind the generation of pseudorandom numbers can be found below...[ref.]

## References:

1. https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html
2. https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html
3.
4.
